### PR TITLE
Add Trac to the list of supported systems

### LINKED ISSUE #113: write backend for Trac
Suggestion: a new Bicho backend that grabs data from Trac bugtrackers. I started on this but stopped and won't be continuing anytime soon; feel free to [take a look at my unfinished work](https://github.com/brainwane/Bicho/blob/trac/Bicho/backends/trac.py). I suggest you use the `xmlrpclib` Python library, and use [the Django project](https://code.djangoproject.com/wiki/OpenData#trac-s-rpc-interface) as a site to test against.

### PR DESCRIPTION
**Pull request by rodrigoprimo**
Fixes #113

### CODE REVIEW

**Comment by jgbarah** [comment]
Thanks a lot! Merging...

**Comment by rodrigoprimo** [comment]
@jgbarah it seems to me that by mistake you closed this PR without merging. Could you please check?

**Comment by jgbarah** [comment]
Oooops. You were right. Sorry.

**Comment by rodrigoprimo** [comment]
No problem, thanks!

**Pull request merged**
